---
# tasks file for demo


- name: debug some variable
  ansible.builtin.debug:
    msg: "This is showing that {{ item.name }} has a value of {{ item.value }}"
  loop: "{{ hash_vars }}"

- name: Different variable
  ansible.builtin.debug:
    msg: "This would pull some information from {{ ocp_hostname }} if it could talk to that cluster!"

- name: Collection of variables
  ansible.builtin.debug:
    msg: "Here's just a list of variables: {{ collection_list }} "
  loop: "{{ collection }}"
  loop_control:
    loop_var: collection_list

# - name: Run a herve4m to make sure the collection is available
#   herve4m.quay.quay_organization:
#     quay_host: "{{ quay_survey_host }}"
#     quay_username: "{{ quay_survey_user }}"
#     quay_password: "{{ quay_survey_password }}"
#     name: test_org
#     state: absent
#     email: kstolee@testing.com